### PR TITLE
Fixes issue #222: Declares all deprecated classes to be subclasses of…

### PR DESCRIPTION
**Pull request by dillerm**
… 'ObsoleteClass'; and creates file that preserves original class hierarchy for deprecated classes.

### CODE REVIEW

**Comment by dillerm** [comment]
@hoganwr is there a subdirectory in this repo that you want the deprecated class file to be moved to?

**Comment by hoganwr** [comment]
No I don't think so. I thought it should live at the top level along with the other "products".

**Comment by hoganwr** [comment]
I reviewed this pull request and it all looks good. Ok to merge and publish the new release.

**Review by hoganwr — APPROVED** [review]
Looks good!

**Pull request merged**
