### PR TITLE
ODK update and stronger QC

### PR DESCRIPTION
**Pull request by matentzn**
- [ ] Merge AFTER #223 and after updating from `main` branch!

### CODE REVIEW

**Comment by dillerm** [comment]
If my understanding is correct, I should be able to merge this with main now, right?

**Comment by matentzn** [comment]
Now, QC is activated. Basically you need to fix all the QC errors thrown up on this branch here, (you can test locally by running `sh run.sh make test IMP=false MIR=false`).

Let me know if you need any help! This will also take care of #222

**Comment by matentzn** [comment]
Dont forget this @dillerm

**Comment by dillerm** [comment]
Getting ready to merge this, but have a quick question about the purpose of the profile.txt file. It lists a bunch of errors/warnings that don't seem to apply to OMRSE so just want to verify that this isn't documenting issues with the ontology.

**Comment by matentzn** [comment]
> Getting ready to merge this, but have a quick question about the purpose of the profile.txt file. It lists a bunch of errors/warnings that don't seem to apply to OMRSE so just want to verify that this isn't documenting issues with the ontology.

No this is purely about the tests the ODK will execute! Remember to not merge this before the tests pass, so merge master into this branch and see if all is ok!

**Comment by hoganwr** [comment]
Thanks Nico!  We will merge main into this branch first, before resolving
the pull request.

**Comment by hoganwr** [comment]
Still one deprected_class_reference error to fix.  Not ready to merge.  We will need to make that fix (and propagate it to main if we don't do it there directly) and then merge main in again to test.

**Comment by hoganwr** [comment]
Ok I made the fix, and now all checks have passed. This looks ok to merge.

**Comment by dillerm** [comment]
@matentzn the "Deploy Docs" qc failed, so I just wanted to ask if there was anything that we overlooked or if this is expected.

**Pull request merged**
